version: '3.1'

services:

  backend:
    container_name: backend-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Pass123!
      POSTGRES_DB: backend